version: '2'

volumes:
  etc_pihole:
  etc_pihole_dnsmasq:
  etc_unbound:

services:
  pihole:
    container_name: pihole-unbound
    image: ayen/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      #- 8443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8001:80/tcp
      - 5335:5335/tcp
    environment:
      ServerIP: ${ServerIP}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "false" # Disable DNSSEC
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_pihole_dnsmasq:/etc/dnsmasq.d:rw
      - etc_unbound:/etc/unbound:rw
    restart: unless-stopped
